# -*- coding: utf-8 -*-
"""
BEER package, test script for simulations with McStas.

See https://europeanspallationsource.se/instruments/beer

See http://www.mcstas.org

Creates McStas instrument file from a template, using actual beam 
geometry definition from beer.geometry and beer.components. 

Tries to compile it and run simulations for BEER reference operation modes 
as defined in beer.modes.

Usage:
------

- Edit the section `Define and check McStas project paths` below to define your 
working environment (default values should work anyway).

- Provide McStas environment variables (MCSTAS, MCSTAS_CC) by passing arguments 
to compileInstr() function below. If they are alredy defined, remove these arguments.

- Run this script from command line: 
`python run_mcstas.py n=[number of neutrons]`

- or from IPyton console:
`%run run_mcstas.py n=[number of neutrons]`


**NOTE**: 

Before execution of simulation, a compiled instrument executable must already 
exist and must be compatible with the instrument file BEER_reference.instr, 
which is generated by `beer.mcstas.parseTemplate()` from the file
`beer/templates/BEER_reference.instr.template`.

Other templates can be used as well, but they must conform to this package 
by defining corresponding tokens for replacement, input arguments etc.


@author: J. Saroun, saroun@ujf.cas.cz
Created on Thu Jun 11 11:10:13 2020
Copyright (c) 2020 Nuclear Physics Institute, CAS, Rez
"""
 

#%% Define functions

import sys
import beer.modes as BMOD
import beer.run as exe

# define number of trials (neutrons) to run:
# can be passed by cmd argument: n=xxx
counts = 1e5

""" Process command arguments 
Accepts n=counts
"""
if len(sys.argv)>1:
    a = sys.argv[1]
    if a.find('=')>0:
        print(sys.argv)
        [pn, pv] = a.split('=')
        if pn=='n':
            counts = int(float(pv))
 
#%% Set McStas environment

exe.mcstasConfig(workpath='', BINPATH=r'C:\mcstas-2.6\bin', MCSTAS=r'C:\mcstas-2.6\lib')


#%% Create and compile default instrument 

# To re-create instrument file (set also force=True to mcstasCompile):
"""
import beer.mcstasexe
beer.mcstasexe.createInstrFile(statinfo=False, shielding=True)
"""

# Compile:
exe.mcstasCompile(statinfo=False, shielding=False, force=False)

#%% Run a single simulation for given BEER mode

"""
data = exe.mcstasRun(modes='PS2', n=counts, docompile=False, plot=True)
"""

#%% Run a sequence of simulations for multiple modes defined in beer.modes
#"""
# define modes to run

# get all modes:
modes = BMOD.getModeKeys() 

# or define own list. Call BMOD.listModes() to get a list of defined modes:
# modes = ['F0', 'PS0', 'M1']
 
# execute simulation for these modes:
data = exe.mcstasRun(modes=modes, n=counts, docompile=False, plot=True)

#"""

