# -*- coding: utf-8 -*-
"""
Scripts for running simulations with McStas.

Usage:

- ``getConfig`` to get default project paths.
- ``setConfig`` to change project paths.
- ``runSimulation`` to run McStas simulation for given BEER reference mode
- ``runModes`` to run a set of simulations for given BEER reference modes

Requires a compiled BEER simulation file ''BEER_reference.exe''.
The instrument source file  BEER_reference.instr is generated by 
`beer.mcstas.parseTemplate()` from the template  
`./templates/BEER_reference.instr.template`.

Created on Thu Jul  2 17:12:07 2020
@author: J. Saroun, saroun@ujf.cas.cz
Copyright (c) 2020 Nuclear Physics Institute, CAS, Rez
"""

import subprocess, os, shutil
import sys
import traceback
from beer.utils import copyResources 
import beer.modes as BMOD
import beer.mcstas.conf as BMC
import beer.mcplot as mcplot
from subprocess import CalledProcessError, TimeoutExpired

#%% Define global variables

# path where the compiled Mcstas instrument is searched for.
userpath = os.path.expanduser('~')
_MCSTAS_PATH = os.path.join(userpath,'beer_optics','mcstas')

# path where Mcstas saves results (adds mode name as subdirectory) 
_MCSTAS_OUT = './'
# name of the compiled McStas instrument executable  
_MCSTAS_INST = 'BEER_reference'

_OUTFILES = ['Lmon.dat', 'TofMon.dat', 'HDivMon.dat', 'VDivMon.dat', 'XMon.dat', 'YMon.dat']

# environment variables for mcstas compiler
_MCSTAS_ENV = {}

#%% Set and verify McStas compiler

def updatePath():
    """
    Update system PATH variable to include path to mcstas bin directory.
    The bin directory is provided as an argument to setMcStas(PATH=...).
    """
    mcstas = getMcStas()
    # update PATH if needed
    if 'PATH' in mcstas:
        path = os.environ['PATH']
        # choose separator
        if sys.platform.startswith('win'):
            sep = ';'
        else:
            sep = ':'
        items = path.split(sep)
        if not mcstas['PATH'] in items:
            os.environ['PATH'] = sep.join([mcstas['PATH'],path])


def setMcStas(version=3, PATH='', MCSTAS='', MCSTAS_CC='', MCSTAS_CFLAGS=''):
    r"""Set environment for McStas.
    
    Leave argument(s) empty if you have defined them as environment variables. 
    
    Parameters
    ----------
    version : int
        Version 2 or 3 of McStas
    PATH:
        Add a path to mcstas compiler to the environment variable PATH
    MCSTAS:
        Set environment variable MCSTAS: McStas path, e.g. C:\mcstas-2.6\lib
    MCSTAS_CC:
        Set environment variable MCSTAS_CC (c compiler, e.g. gcc)
    MCSTAS_CFLAGS:
        Set environment variable MCSTAS_CFLAGS, options for C compiler
    """
    global _MCSTAS_ENV
    _MCSTAS_ENV['version'] = version
    # choose the script file
    if sys.platform.startswith('win'):
        if version==2:
            _MCSTAS_ENV['cmd'] = 'compile.bat'
        else:
            _MCSTAS_ENV['cmd'] = 'compile_v3.bat'
    else:
        if version==2:
            _MCSTAS_ENV['cmd'] = 'compile.sh'
        else:
            _MCSTAS_ENV['cmd'] = 'compile_v3.sh'
    
    # Set environment values from arguments if defined
    e = {}
    if PATH:
        if not os.path.isdir(PATH):
            print('ERROR: Path {} does not exist.'.format(PATH))
        else:
            e['PATH'] = PATH
    if MCSTAS:
        if not os.path.isdir(MCSTAS):
            print('ERROR: Path {} does not exist.'.format(MCSTAS))
        else:
            e['MCSTAS'] = MCSTAS
    if MCSTAS_CFLAGS:
        e['MCSTAS_CFLAGS'] = MCSTAS_CFLAGS
    if MCSTAS_CC:
        e['MCSTAS_CC'] = MCSTAS_CC

    # get missing values from environment:
    qry = ['MCSTAS', 'MCSTAS_CC', 'MCSTAS_CFLAGS']
    env = os.environ
    for q in qry:
        if not q in e:
            if q in env:
                e[q] = env[q]
    # set all variables we have found:
    for var in e:
        _MCSTAS_ENV[var] = e[var]
    

def getMcStas():
    r"""Get environment variables for McStas compiler.
    
    Returns
    -------
    McStas compiler environment as dict with keys:

    PATH:
        Add a path to mcstas compiler to the environment variable PATH
    MCSTAS:
        Set environment variable MCSTAS: McStas path, e.g. C:\mcstas-2.6\lib
    MCSTAS_CC:
        Set environment variable MCSTAS_CC (c compiler, e.g. gcc)
    MCSTAS_CFLAGS:
        Set environment variable MCSTAS_CFLAGS, options for C compiler
    cmd:
        script name for compilation from resources
    """
    global _MCSTAS_ENV
    return _MCSTAS_ENV



def checkConfig(config=None):
    """Check that Mcstas project configuration is correct.
    
    Parameters
    ----------
    config: 
        McStas project configuration in the format returned by getConfig()    
    

    See `getConfig()` for getting information on currect configuration.
    
    See `setConfig()` for setting the configuration.        
        
    """
    # check that all keys are present
    keys = ['WORKPATH','OUTPATH','EXE','INSTR']
    if config is None:
        config = getConfig()
    for key in keys:
        missing = []
        if not key in config:
            missing.append(key)
        if len(missing)>0:
            msg = 'Invalid config format. Missing keys {}'.format(','.join(missing))
            raise Exception('{}: '.format(__file__)+msg)

    sfx = '\n Use setConfig() to define configuration.'
    fmt = '{} {} does not exist\n'
    opath = config['OUTPATH']
    wpath = config['WORKPATH']
    if not os.path.isdir(wpath):
        inp = input("Create workspace directory {} [Y/N]: ")
        if inp == 'Y' or inp=='y': 
            try:
                print('Creating directory: {}'.format(wpath))
                os.makedirs(wpath)
            except Exception as e:
                raise Exception(e)
        if not os.path.isdir(wpath):
            raise Exception(fmt.format('Workspace directory',wpath)+sfx)
    if not os.path.isdir(opath):
        print('Creating output path: {}'.format(opath))
        try:
            os.makedirs(opath)
        except Exception as e:
            raise Exception(e) 
        if not os.path.isdir(opath):
            raise Exception(fmt.format('Output directory',opath)+sfx)


#%% Set up project configuration

def getOutputFiles():
    """
    Return a list of default output filenames of McStas simulation output,
    as defined in the default instrument BEER_reference.instr.
    (generated by beer.mcstas.parseTemplate())
    
    Returns:
    --------
    
    The current list of expected output filenames.
    """
    global _OUTFILES
    return _OUTFILES

def setOutputFiles(fset=None):
    """
    Set a list of default output filenames of McStas simulation output.
    These file will be searched for when handling simulation results.
    
    By default, the list contains:
    'Lmon.dat', 'TofMon.dat', 'HDivMon.dat', 'VDivMon.dat', 'XMon.dat', 'YMon.dat'
    
    Use getOutputFiles() to get current list.
    
    Parameters:
    -----------
    fset: list of str
        Set of filenames saved by the simulation.
    
    """
    global _OUTFILES
    
    if fset:
        _OUTFILES = fset


def getConfig():
    """
    Returns configuration for executing McStas simulation as dict.
        
    Use setConfig() for changing the configuration.
    
    Returns:
    ----------
    
    A dict with keys:
    
    WORKPATH: str
        Path where the compiled Mcstas instrument is searched for.
    INSTR: str
         Name of the McStas instrument (no extensions).
    EXE: str
         File name of the compiled McStas instrument executable, 
         INSTR+'.exe'
    OUTPATH: str
        Path where Mcstas saves results (adds mode name as subdirectory).
        This must be a relative path to the WORKPATH directory.
    """
    
    global _MCSTAS_PATH, _MCSTAS_OUT, _MCSTAS_INST
    res = {}
    res['WORKPATH'] = _MCSTAS_PATH
    res['OUTPATH'] = _MCSTAS_OUT
    res['INSTR'] = _MCSTAS_INST
    res['EXE'] = _MCSTAS_INST+'.exe'
    return res
        

def createWorkspace():
    """Check workspace directories and create missing ones.
    
    Copy resource files to the workspace directory and check the setup 
    (files exist).
    """
    # create workspace directories
    config = getConfig()
    dirs = [config['OUTPATH'], config['WORKPATH']]
    for d in dirs:
        if not os.path.isdir(d):
            try:
                print('Creating directory: {}'.format(d))
                os.makedirs(d)
            except Exception as e:
                print('Failed to create directory: {}'.format(d))
                raise Exception(e)

    # copy resource files to workspace
    if 'cmd' in _MCSTAS_ENV:
        files = [_MCSTAS_ENV['cmd']]
        copyResources(config['WORKPATH'], files=files)
        

def setConfig(workpath='', instname='BEER_reference', outpath='out'):
    """Set McStas project configuration.
    
    Create workspace files and directories if needed. 
    
    Must be executed before calling run* functions from this module.
    
    Parameters
    ----------
    workpath : str
        Root project directory with instrument data and output. 
        If not defined, takes a default path in user profile (./beer_optics/mcstas) 
    instname : str
        Name of the McStas instrument to run. Currently only `BEER_reference` 
        is defined in resources.
    outpath : str
        Path where Mcstas saves results (adds mode name as subdirectory).
        If relative, it is assumed to be a child of `workpath`. 
    
    """
    global _MCSTAS_PATH, _MCSTAS_OUT, _MCSTAS_INST
    
    if workpath:
        _MCSTAS_PATH = os.path.normpath(workpath)
    if outpath:
        if os.path.isabs(outpath):  
            _MCSTAS_OUT = os.path.normpath(outpath)
        else:
            _MCSTAS_OUT = os.path.normpath(os.path.join(_MCSTAS_PATH,outpath))
    if instname:
        _MCSTAS_INST = instname



#%% Create instrument file and compile it

def createInstrument(template='', inpath=None, outpath=None, instname='', 
                     **options):
    """Create McStas instrument file from a template.
    
    The created file is saved in the workspace as defined by :func:`setConfig`. 
    
    The template file is searched for in the package resources, 
    unless `inpath` is defined.
    
    Parameters
    ----------
    template : str
        Template name. If empty, use the instrument name (see :func:`setConfig`)
    inpath: str
        path where to search for instrument template. If not defined, use
        package resources.
    outpath : str
        Path where to save the instrument file (must already exist). 
        If None, use the workspace setting.
    instname : str
        Instrument name (without instr extension). If empty, use the name 
        defined by :func:`setConfig`
    """
    config = getConfig()
    
    if not template:
        template = config['INSTR']+'_3x_GPU'
    if not instname:
        instname = config['INSTR']
    else:
        setConfig(instname=instname)
    if outpath is None:
        outpath = config['WORKPATH']
        checkConfig(config)

    BMC.parseTemplate(instname=instname, 
                  template=template,
                  outpath=outpath, 
                  inpath=inpath,
                  **options)


def compileInstrument(mpi=0, verify=True):
    """
    Attempts to compile instrument file specified in config.
    No validation of McStas compiler is done. It is assumed that
    PATH, MCSTAS and MCSTAS_CC environment variables contain valid info
    on McStas installation.
    
    Parameters:
    -----------
    verify:
        If true, verify first that mcstas is configured properly
        by calling verifyMcStas()
    """
    mcstas = getMcStas()
    # get and check environment
    if verify:
        if not verifyMcStas():
            print('Cannot compile instrument file.')
            return
        env = os.environ
    else:
        # Set environment
        # Set and check environment variables
        env = os.environ
        for v in ['MCSTAS','MCSTAS_CC','MCSTAS_CFLAGS']:
            if v in mcstas:
                env[v] = mcstas[v]
    
    # check that there is instr file to compile
    config = getConfig()
    instfile = os.path.join(config['WORKPATH'],config['INSTR']+'.instr')
    if not os.path.isfile(instfile):
        raise Exception('Instrument file is missing: {}'.format(instfile))
    
    # run compiler using the script compile.* from resources
    res = False
    out = None
    scr = os.path.join(config['WORKPATH'],mcstas['cmd'])
    if not os.path.isfile(scr):
        print('Compilation script not found: "{}"'.format(scr))
        return res
    try:
        # remove *.c file
        fc = os.path.join(config['WORKPATH'],config['INSTR']+'.c')
        if os.path.isfile(fc):
            os.remove(fc)
        
        """
        if 'SHELL' in env:
            cmd = [env['SHELL']]
        else:
            cmd = []
        cmd = cmd + [mcstas['cmd'], config['INSTR']]
        """
        
        cmd = ['mcrun','-c']
        if mpi:
            cmd.append('--mpi={}'.format(mpi))
        cmd.append(config['INSTR']+'.instr')
        cmd.append('-n0') # suppress running, just compile
        # join into one command string - lists may not run on Linux ...
        cmd = ' '.join(cmd)
        print('Command: '+cmd)
        print('Compiling ... ',end='')
# for Python >= 3.7 :
#        out = subprocess.run(cmd, capture_output=True, text=True, shell=True, check=True)
# for Python < 3.7 :
        out = subprocess.run(cmd, cwd=config['WORKPATH'], env=env,
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT, 
                             universal_newlines=True, shell=True, check=True,
                             timeout=1000)
        out.check_returncode()
        print('done.')
        res = True
    except CalledProcessError as e:
        print('failed.')
        msg = 'Can\'t execute {}.\n'.format(cmd)
        msg += 'Return code: {:d}\n'.format(e.returncode)
        if e.stderr: msg += 'stderr:\n'+e.stderr +'\n'
        if e.stdout: msg += 'stdout:\n'+e.stdout +'\n'
        print(msg)
        return res
    except TimeoutExpired as e:
        print('timeout at {} s.'.format(e.timeout))
        return res
    except Exception:
        print('Error while executing {}'.format(cmd))
        traceback.print_exc(file=sys.stdout)
    return res


#%% Run simulations

def verifyConfig(verbose=1):
    """
    Verify workspace configuration.
    """
    res = False
    try:
        config = getConfig()
        checkConfig(config)
        if verbose:
            print('Workspace directory: "{}"'.format(config['WORKPATH']))
            print('Simulation output directory: "{}"'.format(config['OUTPATH']))
            print('McStas instrument executable: {}'.format(config['EXE'])) 
        res = True
    except Exception as e:
        print(e)
    return res


def verifyInstrument(verbose=1):
    """
    Check that compiled instrument file exists.
    If successful, return path to the instrument executable.
    Otherwise returns empty string.
    """
    # check that the executable exists   
    res = ''
    config = getConfig()
    exename = os.path.join(config['WORKPATH'],config['EXE'])
    if not os.path.isfile(exename):
        if verbose:
            mcstas = getMcStas()
            scr = os.path.join(config['WORKPATH'],mcstas['cmd'])
            msg = 'Instrument executable not found, expected {}.\n'.format(exename)
            msg += 'Try to compile the instrument manually. See {}\n'.format(scr)
            print(msg)
    else:
        res = exename
    return res


def verifyMcStas(verbose=1):
    """
    Check McStas compiler environment. Use setMcStas() to define it.
    
    Call verifyMcStas() always before trying to run McStas using this package.
            
    Returns:
    --------
    True if the compilers can be executed.
            
    """
    def testExe(cmd):
        q = False
        out = None
        try:
            if verbose:
                print('\tTesting {} ... '.format(cmd[0]),end='')
            # join into one command string - lists may not run on Linux ...
            cmd = ' '.join(cmd)
            out = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, 
                                 universal_newlines=True, shell=True, check=True)
            out.check_returncode()
            if verbose:
                print('OK.')
                if out.stdout: print(out.stdout)
            q = True
        except CalledProcessError as e:
            print('failed.')
            msg = 'Can\'t execute {}.\n'.format(cmd)
            msg += 'Return code: {:d}\n'.format(e.returncode)
            if e.stderr: msg += 'stderr:\n'+e.stderr +'\n'
            if e.stdout: msg += 'stdout:\n'+e.stdout +'\n'
            print(msg)
            return q
        except TimeoutExpired as e:
            print('timeout at {} s.'.format(e.timeout))
            return q
        except Exception:
            print('Error while executing {}'.format(cmd))
            traceback.print_exc(file=sys.stdout)
        return q
    
    """    
    mcstas = getMcStas()
    config = getConfig()
    

    # Set and check environment variables
    env = os.environ
    for v in ['MCSTAS','MCSTAS_CC','MCSTAS_CFLAGS']:
        if v in mcstas:
            env[v] = mcstas[v]

    msgs = ''
    if not (('MCSTAS' in env) and ('MCSTAS_CC' in env)) :
        msgs += 'ERROR: Environment variables MCSTAS and MCSTAS_CC not defined.'

    if ('MCSTAS' in env) and not os.path.isdir(env['MCSTAS']):
        msgs += 'ERROR: Path {} does not exist.\n'.format(env['MCSTAS'])
        msgs += 'Set environment variable {}.\n'.format('MCSTAS')
    
    scr = os.path.join(config['WORKPATH'],mcstas['cmd'])
    if not os.path.isfile(scr):
        msgs += 'ERROR: Script {} does not exist.'.format(scr)

    if msgs: 
        print(msgs)
        return False 
    
    """
    # update PATH variable
    updatePath()
    # Verify that mcstas can be executed
    res1 = testExe(['mcstas', '--version'])    
    # Verify that C compiler can be executed
    res2 = testExe(['mcrun', '--version'])
    return res1 and res2


def runSimulation(mode, n=10000, mpi=0, verbose=1, npulse=0, timeout=600, 
                  outdir=None, quiet=False, **kwargs):
    """
    Run McStas simulation with given parameters. Optinally plot results.
    
    Parameters:
    -----------
    mode: int or str
        BEER reference mode index or ID
    n: int
        Number of neutrons to run
    verbose: int
        `verbose` parameter passed to McStas instrument file
    npulse: int
        `npulse` parameter passed to McStas instrument file
    timeout: int
        imeout in sec for execution
    outdir: str
        McStas output directory, relative to config['OUTPATH'].
        If not provided, mode ID string is used.
    """
    # verify configuration
    if not verifyConfig(verbose=not quiet):
        return

    # check that the executable exists
    exename = verifyInstrument(verbose=not quiet)     
    if not exename:
        return

    # get configuration
    config = getConfig()
    outpath = os.path.normpath(config['OUTPATH'])

    # get mode info
    if isinstance(mode, int):
        modeid = BMOD.modes[mode]['ID']
        imode = mode
    elif isinstance(mode, str):
        modeid = mode
        imode = BMOD.getModeIndex(mode)
    else:
        raise Exception('Wrong mode parameter: '+mode)
    
    # set output directory
    if outdir:
        outname = os.path.join(outpath,outdir)
    else:
        outname = os.path.join(outpath,modeid)
    
    # define -d parameter 
    # for relative outname, we must take it relative to WORKPATH
    # since simulations run in WORKPATH
    if not os.path.isabs(outname):
        respath = os.path.relpath(outname, config['WORKPATH'])
    else:
        respath = outname
        
    # set up command parameters
    sn = '-n{:d}'.format(int(n))
    smode = 'mode={:d}'.format(imode)
    snpls = 'npulse={:d}'.format(npulse)
    sv = 'verbose={:d}'.format(int(max(0,verbose)))
   
   # ename = os.path.join('.',config['EXE'])
   
    cmd = ['mcrun']
    if mpi:
        cmd.append('--mpi={}'.format(mpi))
    cmd.append(config['INSTR']+'.instr')

    cmd += [sn, smode, sv, snpls]
    for key in kwargs:
        cmd += ['{}={}'.format(key, kwargs[key])]
    cmd += ['-d', respath]
    # clean output path if exists
    if os.path.exists(outname):
        shutil.rmtree(outname)
        
    # try to run it    
    out = None
    res = False
    try:
        cmd = ' '.join(cmd)
        print('Command: '+cmd)
        print('Running ... ',end='')
# for Python >= 3.7 :
#        out = subprocess.run(cmd, capture_output=True, text=True, shell=True, check=True)
# for Python < 3.7 :
        out = subprocess.run(cmd, cwd=config['WORKPATH'], 
                             stdout=subprocess.PIPE, stderr=subprocess.STDOUT, 
                             universal_newlines=True, shell=True, check=True,
                             timeout=timeout)
        out.check_returncode()
        print('done.')
        res = True
    except CalledProcessError as e:
        if verbose: print('failed.')
        msg = 'Can\'t execute {}.\n'.format(cmd)
        msg += 'Return code: {:d}\n'.format(e.returncode)
        if e.stderr: msg += 'stderr:\n'+e.stderr +'\n'
        if e.stdout: msg += 'stdout:\n'+e.stdout +'\n'
        print(msg)
        return res
    except TimeoutExpired as e:
        if verbose: print('timeout at {} s.'.format(e.timeout))
        return res
    except Exception:
        print('Error while executing {}'.format(cmd))
        traceback.print_exc(file=sys.stdout)
    if res and out.stdout:
        if not quiet: print(out.stdout)
        # save stdout in log file
        fout = os.path.join(outname,modeid+'.log')
        with open(fout, 'w') as f: 
            f.write(out.stdout)
            f.close()
        print('See results in "{}"\n'.format(outname))
    return res                            


def runModes(modes=[], counts=1e6, timeout=3600, **kwargs):
    
    """
    Run simulations for selected BEER reference modes.
    
    Parameters:
    -----------
    modes: list
        List of mode ID's
    counts: int
        Number of neutrons to trace.
    timeout: int
        Timeout in sec for one simulation
    
    Example:
    --------
    
    runModes(modes=['F1','PS1','MCA', 'IM0'])
    """

    # check configuration
    if not verifyConfig():
        return
    
    # check that the executable exists    
    exename = verifyInstrument()
    if not exename:
        return

    # DS1 must be run for the two wavelength frames separately
    if 'DS1' in modes:
        modes.remove('DS1')
        if not 'DS1_0' in modes:
            modes.extend(['DS1_0','DS1_-1'])
        if not 'DS1_-1' in modes:
            modes.extend(['DS1_0','DS1_-1'])
    res = (len(modes)>0)
    for m in modes:
        m = m.strip()
        sm = m.split('_')
        npls=0
        if (len(sm)>1):
            print(sm)
            print(''.join(sm[1:]))
            npls = int(''.join(sm[1:]))
        imode = BMOD.getModeIndex(sm[0])
        if (imode>=0):
            try:
                res = res and runSimulation(sm[0], n=counts, npulse=npls, 
                                  timeout=timeout, outdir=m, quiet=True, **kwargs)
            except Exception as e:
                print(e)
    return res 


#%% Process and plot results

def processResults(results, dataname='Lmon.dat', outfile='intensities.dat'):
    """
    Process a set of simulation results from McStas or SIMRES. 
    For each result, find given data file (dataname) and convert it 
    to the Data1D object. Print and (optionally) save the integral intensities 
    for all results as a table.    
    
    Each simulation result is saved in a separate directory, `results` is 
    a list of these directories (relative to `parentdir').
    
    `Example: results=['FC1', 'PSC1', 'MCA'], dataname='xmon.dat'` 
    
    would process all files 'xmon.dat' found in the subdirectories 
    'FC1', 'PS1' and 'MCA' relative to the workspace outpuut directory. 
    
    Parameters:
    -----------
    results: list of str
        list of directories (McStas) or file name bases (SIMRES) to search for
    dataname: str
        file name (McStas) or file name suffix (SIMRES) to search for
    outfile: str
        output file name
        
    """
    config = getConfig()
    if 'DS1' in results:
        results.remove('DS1')
        if not 'DS1_0' in results:
            results.extend(['DS1_0','DS1_-1'])
        if not 'DS1_-1' in results:
            results.extend(['DS1_0','DS1_-1'])

    datas = mcplot.processResults(results, 
                                  dataname=dataname, 
                                  parentdir=config['OUTPATH'],
                                  outfile=outfile,
                                  dformat='mcstas')
    return datas


def processRun(mode):
    """
    Process a single simulation results produced by McStas. 
    Find all specified files in given directory for given mode and convert them 
    to the `Data1D` objects. Return these objects as a list.
    
    The output file names are assumed to conform to this package, that is:
        
        `base/suffix.dat`
    
    where `base` is the directory name equal to the mode ID, 
    `suffix` denotes the monitor output file name, 
    for example `FC1/Lmon.dat` for wavelength distribution, mode=`FC1`.
        
    Parameters:
    -----------
    mode: str
        mode ID, one of those defined in beer.modes
    
    Returns:
    --------
    
    Retrieved results as Data1D objects.
        
    """
    
    config = getConfig()
    datas = mcplot.processRun(mode, 
                          files=getOutputFiles(), 
                          parentdir=config['OUTPATH'], 
                          dformat='mcstas')    
    return datas


def plotResults(datas, title='McStas', pdf=''):
    """
    Plot results retrieved by processResults(). 
    
    Parameters:
    -----------
    datas: 
        list of Data1D objects
    title: str
        Title to be shown on graph
    pdf: str
        File name to export (pdf format, without extension).
        Leave empty to suppress file export.
        
    """
    if pdf:
        config = getConfig()
        out = os.path.join(config['OUTPATH'],pdf)
    else:
        out = ''
    mcplot.plotDataSet(datas, title=title, pdf=out)

